let menuJSON =
  [
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 130836,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "/AccountsManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170977,
      "SubModule": "Chart of Account",
      "SubModuleOrder": "1",
      "Url": "/AccountsManagement/AccountHead/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170978,
      "SubModule": "Journal Voucher",
      "SubModuleOrder": "2",
      "Url": "/AccountsManagement/JournalVoucher/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170983,
      "SubModule": "Financial Year",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/FinancialYear/List",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170984,
      "SubModule": "Ledger",
      "SubModuleOrder": "3",
      "Url": "/AccountsManagement/Ledger/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170987,
      "SubModule": "Voucher Setting",
      "SubModuleOrder": "6",
      "Url": "/AccountsManagement/VoucherSetting/List",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170988,
      "SubModule": "Bank",
      "SubModuleOrder": "7",
      "Url": "/AccountsManagement/Bank/List",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170989,
      "SubModule": "Bank Account",
      "SubModuleOrder": "6",
      "Url": "/AccountsManagement/BankAccount/Index",
      "IsParent": false,
      "ParentID": "181108"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170990,
      "SubModule": "Bank Receipt Voucher",
      "SubModuleOrder": "7",
      "Url": "/AccountsManagement/BankReceiptVoucher/List",
      "IsParent": false,
      "ParentID": "181108"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170991,
      "SubModule": "Bank Payment Voucher",
      "SubModuleOrder": "8",
      "Url": "/AccountsManagement/BankPaymentVoucher/List",
      "IsParent": false,
      "ParentID": "181108"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 171048,
      "SubModule": "UnPosted Voucher",
      "SubModuleOrder": "9",
      "Url": "/AccountsManagement/UnpostedVoucher/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181109,
      "SubModule": "Instrument Type",
      "SubModuleOrder": "8",
      "Url": "/AccountsManagement/InstrumentType/Index",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181121,
      "SubModule": "Vendor Ledger",
      "SubModuleOrder": "10",
      "Url": "/AccountsManagement/VendorLedger/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181122,
      "SubModule": "Customer Ledger",
      "SubModuleOrder": "11",
      "Url": "/AccountsManagement/CustomerLedger/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181123,
      "SubModule": "Bank Card",
      "SubModuleOrder": "12",
      "Url": "/AccountsManagement/BankCard/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181144,
      "SubModule": "Manage PDCs Received",
      "SubModuleOrder": "9",
      "Url": "/AccountsManagement/PDCsManagement/List",
      "IsParent": false,
      "ParentID": "181108"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181154,
      "SubModule": "Tax Return Schedule",
      "SubModuleOrder": "4",
      "Url": "/CompanyManagement/TaxReturnSchedule/Index",
      "IsParent": false,
      "ParentID": "181173"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181171,
      "SubModule": "Purchase Ledger",
      "SubModuleOrder": "4",
      "Url": "/AccountsManagement/InvoiceLedger/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181172,
      "SubModule": "Sales Ledger",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/SalesLedger/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181195,
      "SubModule": "Accounts Entries",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/AccountingEntries/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181205,
      "SubModule": "Account Setup",
      "SubModuleOrder": "1",
      "Url": "/AccountsManagement/AccountSetp/Index",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181210,
      "SubModule": "Trial Balance",
      "SubModuleOrder": "2",
      "Url": "/AccountsManagement/TrialBalance/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 201214,
      "SubModule": "Tax Group Setup",
      "SubModuleOrder": "1",
      "Url": "/CompanyManagement/TaxGroupSetup/Index",
      "IsParent": false,
      "ParentID": "181173"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 201239,
      "SubModule": "PDCs Status Report",
      "SubModuleOrder": "13",
      "Url": "/AccountsManagement/Reports/PDCsStatus",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211284,
      "SubModule": "Journal Voucher Report",
      "SubModuleOrder": "14",
      "Url": "/AccountsManagement/Reports/JournalVoucher",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211285,
      "SubModule": "Bank Payment Voucher Report",
      "SubModuleOrder": "15",
      "Url": "/AccountsManagement/Reports/BankPaymentVouchers",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211311,
      "SubModule": "Financial Year Closing",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/FinancialYearClosing/Index",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211315,
      "SubModule": "Bank Receipt Voucher Report",
      "SubModuleOrder": "16",
      "Url": "/AccountsManagement/Reports/BankReceiptVouchers",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211324,
      "SubModule": "Trial Balance Report",
      "SubModuleOrder": "17",
      "Url": "/AccountsManagement/Reports/TrialBalance",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211325,
      "SubModule": "General Ledger Report",
      "SubModuleOrder": "18",
      "Url": "/AccountsManagement/Reports/GeneralLedger",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211326,
      "SubModule": "Account Receivable Report",
      "SubModuleOrder": "19",
      "Url": "/AccountsManagement/Reports/AccountReceivables",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211327,
      "SubModule": "Customer Invoice Receivables Report",
      "SubModuleOrder": "20",
      "Url": "/AccountsManagement/Reports/CustomerInvoiceReceivables",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211328,
      "SubModule": "Vendor Invoice Payable Report",
      "SubModuleOrder": "21",
      "Url": "/AccountsManagement/Reports/VendorInvoicePayable",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211338,
      "SubModule": "Bank Summary Report",
      "SubModuleOrder": "22",
      "Url": "/AccountsManagement/Reports/BankBalanceSummary",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211364,
      "SubModule": "Journal Voucher Payroll",
      "SubModuleOrder": "3",
      "Url": "/AccountsManagement/JournalVoucherPayroll/Index",
      "IsParent": false,
      "ParentID": "170976"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211369,
      "SubModule": "VAT Return",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/VATReturn/Detail",
      "IsParent": false,
      "ParentID": "181173"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211373,
      "SubModule": "Test Screen",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/FinancialYear/ListS",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211374,
      "SubModule": "Tester",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/FinancialYear/Listss",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211375,
      "SubModule": "Tester",
      "SubModuleOrder": "5",
      "Url": "/AccountsManagement/FinancialYear/Listss",
      "IsParent": false,
      "ParentID": "28"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211377,
      "SubModule": "Bank Payment Detailed Report",
      "SubModuleOrder": "23",
      "Url": "/AccountsManagement/Reports/BankPayments",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211378,
      "SubModule": "Bank Receipt Detailed Report",
      "SubModuleOrder": "24",
      "Url": "/AccountsManagement/Reports/BankReceipts",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211384,
      "SubModule": "Payables Aging Summary",
      "SubModuleOrder": "25",
      "Url": "/AccountsManagement/Reports/PayablesAgingSummary",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211385,
      "SubModule": "Receivables Aging Summary",
      "SubModuleOrder": "26",
      "Url": "/AccountsManagement/Reports/ReceivablesAgingSummary",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 211387,
      "SubModule": "Bank Ledger Report",
      "SubModuleOrder": "27",
      "Url": "/AccountsManagement/Reports/BankLedger",
      "IsParent": false,
      "ParentID": "201238"
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171022,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/AssetManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171025,
      "SubModule": "Item Category",
      "SubModuleOrder": "1",
      "Url": "/AssetManagement/AssetItemCategory/Index",
      "IsParent": false,
      "ParentID": "171024"
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171026,
      "SubModule": "Asset Type",
      "SubModuleOrder": "2",
      "Url": "/AssetManagement/AssetType/Index",
      "IsParent": false,
      "ParentID": "171024"
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171027,
      "SubModule": "Asset Profile",
      "SubModuleOrder": "1",
      "Url": "/AssetManagement/AssetProfile/Index",
      "IsParent": false,
      "ParentID": "171023"
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171033,
      "SubModule": "Asset Assignment",
      "SubModuleOrder": "2",
      "Url": "/AssetManagement/AssetAssignment/Index",
      "IsParent": false,
      "ParentID": "171023"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 10208,
      "SubModule": "Leave Type",
      "SubModuleOrder": "1",
      "Url": "/AttendanceManagement/LeaveType/Index",
      "IsParent": false,
      "ParentID": "50616"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 20554,
      "SubModule": "Leave Approval",
      "SubModuleOrder": "2",
      "Url": "/AttendanceManagement/LeaveApproval/Index",
      "IsParent": false,
      "ParentID": "171020"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 130838,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/AttendanceManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 130859,
      "SubModule": "Leave Request",
      "SubModuleOrder": "1",
      "Url": "/AttendanceManagement/LeaveRequest/Index",
      "IsParent": false,
      "ParentID": "171020"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 171019,
      "SubModule": "Leave Quota",
      "SubModuleOrder": "2",
      "Url": "/AttendanceManagement/LeaveQuota/Index",
      "IsParent": false,
      "ParentID": "50616"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 171021,
      "SubModule": "Shift Type",
      "SubModuleOrder": "3",
      "Url": "/AttendanceManagement/ShiftType/Index",
      "IsParent": false,
      "ParentID": "50616"
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 171030,
      "SubModule": "Shift",
      "SubModuleOrder": "3",
      "Url": "/AttendanceManagement/Shift/Index",
      "IsParent": false,
      "ParentID": "171020"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 170985,
      "SubModule": "Cash Receipt Voucher",
      "SubModuleOrder": "1",
      "Url": "/CashCenter/CashReceiptVoucher/List",
      "IsParent": false,
      "ParentID": "211290"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 170986,
      "SubModule": "Cash Payment Voucher",
      "SubModuleOrder": "2",
      "Url": "/CashCenter/CashPaymentVoucher/List",
      "IsParent": false,
      "ParentID": "211290"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211286,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "/CashCenter/Dashboard",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211288,
      "SubModule": "Cash Handler Role",
      "SubModuleOrder": "1",
      "Url": "/CashCenter/CashHandler/Role",
      "IsParent": false,
      "ParentID": "211287"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211289,
      "SubModule": "Assign Cash Handler Role",
      "SubModuleOrder": "2",
      "Url": "/CashCenter/CashHandler/Assign",
      "IsParent": false,
      "ParentID": "211287"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211292,
      "SubModule": "Role Type",
      "SubModuleOrder": "1",
      "Url": "/CashCenter/Setup/RoleType",
      "IsParent": false,
      "ParentID": "211291"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211294,
      "SubModule": "Pay Cash",
      "SubModuleOrder": "3",
      "Url": "/CashCenter/PayCash/List",
      "IsParent": false,
      "ParentID": "211287"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211295,
      "SubModule": "Balances Summary",
      "SubModuleOrder": "4",
      "Url": "/CashCenter/PayCash/BalancesSummary",
      "IsParent": false,
      "ParentID": "211287"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211322,
      "SubModule": "Cash Receipt Voucher Report",
      "SubModuleOrder": "1",
      "Url": "/CashCenter/Reports/CashReceiptVouchers",
      "IsParent": false,
      "ParentID": "211321"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211323,
      "SubModule": "Cash Payment Voucher Report",
      "SubModuleOrder": "2",
      "Url": "/CashCenter/Reports/CashPaymentVouchers",
      "IsParent": false,
      "ParentID": "211321"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 40567,
      "SubModule": "Audit Log Report",
      "SubModuleOrder": "0",
      "Url": "/UserManagement/AuditLogReport/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 130793,
      "SubModule": "Company Project",
      "SubModuleOrder": "4",
      "Url": "/UserManagement/RefCompanyProject/Index",
      "IsParent": false,
      "ParentID": "140942"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 130856,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/UserManagement/Dashboard/Index",
      "IsParent": false,
      "ParentID": "0"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 130892,
      "SubModule": "Compose Email",
      "SubModuleOrder": "8",
      "Url": "/UserManagement/ComposeEmail/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 140943,
      "SubModule": "Company Setup",
      "SubModuleOrder": "1",
      "Url": "/CompanyManagement/CompanyList/Index",
      "IsParent": false,
      "ParentID": "140942"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 181184,
      "SubModule": "User Setup",
      "SubModuleOrder": "1",
      "Url": "/UserManagement/UserSetup/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 181197,
      "SubModule": "Region Setup",
      "SubModuleOrder": "1",
      "Url": "/UserManagement/RegionSetup/Index",
      "IsParent": false,
      "ParentID": "130792"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 181201,
      "SubModule": "ERP Messages",
      "SubModuleOrder": "2",
      "Url": "/UserManagement/ERPMessages/Index",
      "IsParent": false,
      "ParentID": "130792"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 201222,
      "SubModule": "Sub Module",
      "SubModuleOrder": "10",
        "Url": "/Core/SubModule/List",
      "IsParent": false,
      "ParentID": "130792"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 201223,
      "SubModule": "Module",
      "SubModuleOrder": "9",
        "Url": "/Core/Module/List",
      "IsParent": false,
      "ParentID": "130792"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 211302,
      "SubModule": "User Activity Log",
      "SubModuleOrder": "3",
      "Url": "/UserManagement/UserActivityLog/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 211320,
      "SubModule": "Document Setup",
      "SubModuleOrder": "11",
      "Url": "/UserManagement/DocumentSetup/Index",
      "IsParent": false,
      "ParentID": "140942"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 211330,
      "SubModule": "Role Rights Template",
      "SubModuleOrder": "12",
      "Url": "/UserManagement/RoleRights/Index",
      "IsParent": false,
      "ParentID": "130792"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 211341,
      "SubModule": "Bulk Upload Data",
      "SubModuleOrder": "20",
      "Url": "/UserManagement/BulkUploadData/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 211379,
      "SubModule": "Transaction Data Upload",
      "SubModuleOrder": "21",
      "Url": "/UserManagement/BulkTransitionData/Index",
      "IsParent": false,
      "ParentID": "1"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 201247,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": null,
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211248,
      "SubModule": "Assets",
      "SubModuleOrder": "1",
      "Url": "/FixedAssets/Assets/List",
      "IsParent": false,
      "ParentID": "201249"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211249,
      "SubModule": "Setups",
      "SubModuleOrder": "1",
      "Url": "/FixedAssets/Setup/Screens",
      "IsParent": false,
      "ParentID": "201250"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211252,
      "SubModule": "Depreciation",
      "SubModuleOrder": "2",
      "Url": "/FixedAssets/Assets/Depreciation",
      "IsParent": false,
      "ParentID": "201249"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211254,
      "SubModule": "Assets Report",
      "SubModuleOrder": "1",
      "Url": "/FixedAssets/Reports/Assets",
      "IsParent": false,
      "ParentID": "211253"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211255,
      "SubModule": "Depreciation Report",
      "SubModuleOrder": "2",
      "Url": "/FixedAssets/Reports/Depreciation",
      "IsParent": false,
      "ParentID": "211253"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211256,
      "SubModule": "Purchase Order",
      "SubModuleOrder": "4",
      "Url": "/FixedAssets/PurchaseOrder/List",
      "IsParent": false,
      "ParentID": "201249"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211261,
      "SubModule": "Purchase Invoice",
      "SubModuleOrder": "5",
      "Url": "/FixedAssets/PurchaseInvoice/List",
      "IsParent": false,
      "ParentID": "201249"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211376,
      "SubModule": "Fixed Asset Register",
      "SubModuleOrder": "3",
      "Url": "/FixedAssets/Register/List",
      "IsParent": false,
      "ParentID": "201249"
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211386,
      "SubModule": "Excel Upload",
      "SubModuleOrder": "2",
      "Url": "/FixedAssets/ExcelUpload/Add",
      "IsParent": false,
      "ParentID": "201250"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 10132,
      "SubModule": "Employee",
      "SubModuleOrder": "1",
      "Url": "/HRManagement/EmployeeList/Index",
      "IsParent": false,
      "ParentID": "10131"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 10136,
      "SubModule": "Employee Directory",
      "SubModuleOrder": "7",
      "Url": "/HRManagement/EmployeeList/EmployeeDirectory/Index",
      "IsParent": false,
      "ParentID": "10131"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 130837,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/HRManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 181208,
      "SubModule": "HR Settings",
      "SubModuleOrder": "1",
      "Url": "/HRManagement/HRSetup/Screens",
      "IsParent": false,
      "ParentID": "10116"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 181209,
      "SubModule": "HR Section Setup",
      "SubModuleOrder": "2",
      "Url": "/HRManagement/HRJoinSetup/Screens",
      "IsParent": false,
      "ParentID": "10116"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 211309,
      "SubModule": "Organization Chart",
      "SubModuleOrder": "8",
      "Url": "/HRManagement/OrganizationChart/Index",
      "IsParent": false,
      "ParentID": "10131"
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 211313,
      "SubModule": "Master Staff Payroll Report",
      "SubModuleOrder": "1",
      "Url": "/HRManagement/Reports/MasterStaffPayroll",
      "IsParent": false,
      "ParentID": "211312"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181113,
      "SubModule": "Maintenance Request",
      "SubModuleOrder": "1",
      "Url": "/JobRequestCenter/MaintenanceRequest/List",
      "IsParent": false,
      "ParentID": "181111"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181114,
      "SubModule": "Maintenance Types",
      "SubModuleOrder": "1",
      "Url": "/JobRequestCenter/MaintenanceType/Detail",
      "IsParent": false,
      "ParentID": "181112"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181124,
      "SubModule": "Requestee Types",
      "SubModuleOrder": "2",
      "Url": "/JobRequestCenter/RequesteeType/Detail",
      "IsParent": false,
      "ParentID": "181112"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181165,
      "SubModule": "Job Card",
      "SubModuleOrder": "4",
      "Url": "/JobRequestCenter/JobCard/List",
      "IsParent": false,
      "ParentID": "181111"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181166,
      "SubModule": "Job Request Status",
      "SubModuleOrder": "3",
      "Url": "/JobRequestCenter/Status/Detail",
      "IsParent": false,
      "ParentID": "181112"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181168,
      "SubModule": "Job Card Status",
      "SubModuleOrder": "4",
      "Url": "/JobRequestCenter/JobCard/Status",
      "IsParent": false,
      "ParentID": "181112"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 201237,
      "SubModule": "Job Requests Report",
      "SubModuleOrder": "1",
      "Url": "/JobRequestCenter/Reports/Requests",
      "IsParent": false,
      "ParentID": "201236"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 201240,
      "SubModule": "Job Cards Report",
      "SubModuleOrder": "2",
      "Url": "/JobRequestCenter/Reports/JobCards",
      "IsParent": false,
      "ParentID": "201236"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211297,
      "SubModule": "Profile",
      "SubModuleOrder": "2",
      "Url": "/LandlordPortal/Profile/Index",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211298,
      "SubModule": "Unit",
      "SubModuleOrder": "3",
      "Url": "/LandlordPortal/Unit/List",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211299,
      "SubModule": "Agreement",
      "SubModuleOrder": "4",
      "Url": "/LandlordPortal/LeaseAgreement/List",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211300,
      "SubModule": "Maintenance Request",
      "SubModuleOrder": "5",
      "Url": "/LandlordPortal/MaintenanceRequest/List",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211301,
      "SubModule": "Property",
      "SubModuleOrder": "2",
      "Url": "/LandlordPortal/Property/List",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211303,
      "SubModule": "Profile",
      "SubModuleOrder": "1",
      "Url": "/LandlordPortal/Profile",
      "IsParent": false,
      "ParentID": "211296"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 10201,
      "SubModule": "Pay Slip",
      "SubModuleOrder": "4",
      "Url": "/PayrollManagement/PaySlip/Index",
      "IsParent": false,
      "ParentID": "10193"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 40582,
      "SubModule": "Tax Slabs",
      "SubModuleOrder": "2",
      "Url": "/PayrollManagement/TaxSlabs/Index",
      "IsParent": false,
      "ParentID": "10193"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 40583,
      "SubModule": "Tax Ordinance Act",
      "SubModuleOrder": "1",
      "Url": "/PayrollManagement/TaxMaster/Index",
      "IsParent": false,
      "ParentID": "10193"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 40585,
      "SubModule": "Loan",
      "SubModuleOrder": "3",
      "Url": "/PayrollManagement/Loan/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 40586,
      "SubModule": "Loan Approval",
      "SubModuleOrder": "5",
      "Url": "/PayrollManagement/LoanApproval/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 50652,
      "SubModule": "Loan Profile",
      "SubModuleOrder": "4",
      "Url": "/PayrollManagement/LoanPlan/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 130839,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/PayrollManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 171034,
      "SubModule": "Payroll Payment",
      "SubModuleOrder": "8",
      "Url": "/PayrollManagement/PayrollPayment/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 181204,
      "SubModule": "Head Setup",
      "SubModuleOrder": "1",
      "Url": "/PayrollManagement/HeadSetup/Index",
      "IsParent": false,
      "ParentID": "10193"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 211283,
      "SubModule": "Payroll Register",
      "SubModuleOrder": "7",
      "Url": "/PayrollManagement/PayrollRegisterMaster/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 211310,
      "SubModule": "Payroll Register Setup",
      "SubModuleOrder": "6",
      "Url": "/PayrollManagement/PayrollSetup/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 211361,
      "SubModule": "Variable Payroll",
      "SubModuleOrder": "9",
      "Url": "/PayrollManagement/PayrollVariant/Index",
      "IsParent": false,
      "ParentID": "171018"
    },
    {
      "ModuleID": 13,
      "Module": "Point Of Sale",
      "ModuleOrder": 25,
      "SubModuleID": 181097,
      "SubModule": "POS",
      "SubModuleOrder": "2",
      "Url": "/PointOfSale/SaleInvoice/Add",
      "IsParent": false,
      "ParentID": "181095"
    },
    {
      "ModuleID": 13,
      "Module": "Point Of Sale",
      "ModuleOrder": 25,
      "SubModuleID": 211337,
      "SubModule": "Setups",
      "SubModuleOrder": "1",
      "Url": "/PointOfSale/Setup/Screens",
      "IsParent": false,
      "ParentID": "211336"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140953,
      "SubModule": "Dashboard",
      "SubModuleOrder": "0",
      "Url": "/ProductManagement/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140957,
      "SubModule": "Product",
      "SubModuleOrder": "0",
      "Url": "/ProductManagement/Product/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140958,
      "SubModule": "Bin No",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/BinNo/Index",
      "IsParent": false,
      "ParentID": "170975"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140962,
      "SubModule": "Zone",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/Zone/Index",
      "IsParent": false,
      "ParentID": "170975"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140966,
      "SubModule": "Shelf",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/Shelf/Index",
      "IsParent": false,
      "ParentID": "170975"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140967,
      "SubModule": "Warehouse",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/Warehouse/Index",
      "IsParent": false,
      "ParentID": "170975"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 170972,
      "SubModule": "Inventory Register",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/InventoryStock/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 170993,
      "SubModule": "Bill of Materials",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/BillofMaterials/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 171016,
      "SubModule": "Place Assembly Order",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/PlaceAssemblyOrder/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 171017,
      "SubModule": "Assembly Order",
      "SubModuleOrder": "5",
      "Url": "/ProductManagement/AssemblyOrder/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 181200,
      "SubModule": "Item Setups",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/ItemSetups/Index",
      "IsParent": false,
      "ParentID": "140944"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 201220,
      "SubModule": "Test Module",
      "SubModuleOrder": "5",
      "Url": null,
      "IsParent": false,
      "ParentID": "140944"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 201241,
      "SubModule": "Product Brand",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/ProductBrand/Index",
      "IsParent": false,
      "ParentID": "140944"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211258,
      "SubModule": "Price List",
      "SubModuleOrder": "6",
      "Url": "/ProductManagement/PriceList/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211260,
      "SubModule": "Standard Price List",
      "SubModuleOrder": "7",
      "Url": "/ProductManagement/StandardPriceList/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211279,
      "SubModule": "Standard Price Setup",
      "SubModuleOrder": "8",
      "Url": "/ProductManagement/StandardPriceSetup/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211282,
      "SubModule": "Campaign Price Setup",
      "SubModuleOrder": "9",
      "Url": "/ProductManagement/CampaignPriceMain/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211340,
      "SubModule": "Items List Report",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/Reports/ItemsList",
      "IsParent": false,
      "ParentID": "211339"
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211344,
      "SubModule": "Quantity Register",
      "SubModuleOrder": "26",
      "Url": "/ProductManagement/QuantityRegister/Index",
      "IsParent": false,
      "ParentID": "140956"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171051,
      "SubModule": "Landlord",
      "SubModuleOrder": "1",
      "Url": "/RealEstate/PropertyOwner/List",
      "IsParent": false,
      "ParentID": "181186"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171053,
      "SubModule": "Property",
      "SubModuleOrder": "1",
      "Url": "/RealEstate/Property/List",
      "IsParent": false,
      "ParentID": "171054"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171058,
      "SubModule": "Units",
      "SubModuleOrder": "2",
      "Url": "/RealEstate/Unit/List",
      "IsParent": false,
      "ParentID": "171054"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171059,
      "SubModule": "Tenant",
      "SubModuleOrder": "1",
      "Url": "/RealEstate/Tenant/List",
      "IsParent": false,
      "ParentID": "181187"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171062,
      "SubModule": "Quotation",
      "SubModuleOrder": "1",
      "Url": "/RealEstate/Quotation/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171063,
      "SubModule": "Lease Agreement",
      "SubModuleOrder": "3",
      "Url": "/RealEstate/LeaseAgreement/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181087,
      "SubModule": "Lease Template",
      "SubModuleOrder": "2",
      "Url": "/RealEstate/LeaseTemplate/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181146,
      "SubModule": "Properties List Report",
      "SubModuleOrder": "1",
      "Url": "/RealEstate/Reports/Properties",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181147,
      "SubModule": "Unit Status Report",
      "SubModuleOrder": "2",
      "Url": "/RealEstate/Reports/PropertyWiseUnits",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181149,
      "SubModule": "Property Wise Unit(s) Status Report",
      "SubModuleOrder": "2",
      "Url": "/RealEstate/Reports/AvailableUnits",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181150,
      "SubModule": "Lease Agreements Report",
      "SubModuleOrder": "5",
      "Url": "/RealEstate/Reports/ActiveAgreements",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181151,
      "SubModule": "Expiring Leases Report",
      "SubModuleOrder": "6",
      "Url": "/RealEstate/Reports/ExpiringAgreements",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181152,
      "SubModule": "Tenants List Report",
      "SubModuleOrder": "7",
      "Url": "/RealEstate/Reports/Tenants",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181153,
      "SubModule": "Landlords List Report",
      "SubModuleOrder": "8",
      "Url": "/RealEstate/Reports/Landlords",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181167,
      "SubModule": "Makani",
      "SubModuleOrder": "5",
      "Url": "/RealEstate/Makani/List",
      "IsParent": false,
      "ParentID": "171054"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181188,
      "SubModule": "Rent Invoices",
      "SubModuleOrder": "4",
      "Url": "/RealEstate/RentInvoices/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181196,
      "SubModule": "Move-Out Requests",
      "SubModuleOrder": "6",
      "Url": "/RealEstate/MoveOutRequests/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181198,
      "SubModule": "Setups",
      "SubModuleOrder": "24",
      "Url": "/RealEstate/Setup/Screens",
      "IsParent": false,
      "ParentID": "171057"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181202,
      "SubModule": "Move-In Checklist",
      "SubModuleOrder": "7",
      "Url": "/RealEstate/MoveInCheckList/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 201217,
      "SubModule": "Master Lease Income Report",
      "SubModuleOrder": "9",
      "Url": "/RealEstate/Reports/MasterLeaseIncome",
      "IsParent": false,
      "ParentID": "181145"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 211304,
      "SubModule": "Due Invoices",
      "SubModuleOrder": "5",
      "Url": "/RealEstate/DueInvoices/List",
      "IsParent": false,
      "ParentID": "181185"
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 211356,
      "SubModule": "Excel Upload",
      "SubModuleOrder": "25",
      "Url": "/RealEstate/ExcelUpload/Add",
      "IsParent": false,
      "ParentID": "171057"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 40594,
      "SubModule": "Head",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/Heads/Index",
      "IsParent": false,
      "ParentID": "40593"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 40595,
      "SubModule": "Payment Plan",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/installmentPlans/Index",
      "IsParent": false,
      "ParentID": "40593"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 40597,
      "SubModule": "Booking",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/Booking/Index",
      "IsParent": false,
      "ParentID": "40596"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 40606,
      "SubModule": "Sales Agent Type",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/SalesAgentType/Index",
      "IsParent": false,
      "ParentID": "40600"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 50606,
      "SubModule": "Challan Generation",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/SingleChallan/Index",
      "IsParent": false,
      "ParentID": "40599"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 50608,
      "SubModule": "Outstanding Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/DefaulterReport/Index",
      "IsParent": false,
      "ParentID": "40601"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 80653,
      "SubModule": "Deal",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/Deal/Index",
      "IsParent": false,
      "ParentID": "80652"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90687,
      "SubModule": "Property Member Bookings Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/MemberBookingReportMaster/Index",
      "IsParent": false,
      "ParentID": "90686"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90693,
      "SubModule": "Property Deals Bookings Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/PropertyDealBookingReportMaster/Index",
      "IsParent": false,
      "ParentID": "90692"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90698,
      "SubModule": "Members Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/MemberReportMaster/Index",
      "IsParent": false,
      "ParentID": "90697"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90704,
      "SubModule": "Property Deals Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/PropertyDealReportMaster/Index",
      "IsParent": false,
      "ParentID": "90703"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90709,
      "SubModule": "Rental Tenants Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/RentalTenantReportMaster/Index",
      "IsParent": false,
      "ParentID": "90708"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 90719,
      "SubModule": "Property Sales Master Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/PropertySaleReportMaster/Index",
      "IsParent": false,
      "ParentID": "90718"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 130791,
      "SubModule": "Project Summary report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/MasterSummaryForProject/Index",
      "IsParent": false,
      "ParentID": "130790"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 130809,
      "SubModule": "Booking Challan Generation",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/ReportBookingChallan/Index",
      "IsParent": false,
      "ParentID": "130808"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 130914,
      "SubModule": "Advance Token Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/AdvanceTokenReport/Index",
      "IsParent": false,
      "ParentID": "130912"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140928,
      "SubModule": "Projected Recovery Summary Report",
      "SubModuleOrder": "1",
      "Url": "/PropertySalesManagement/ProjectedRecoveryReport/Index",
      "IsParent": false,
      "ParentID": "140927"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140980,
      "SubModule": "DashBoard",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/SalesDashBoard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140981,
      "SubModule": "Sale Invoice",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/SalesInvoice/Index",
      "IsParent": false,
      "ParentID": "140978"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140983,
      "SubModule": "VAT Posting Group",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/VATPostingGrp",
      "IsParent": false,
      "ParentID": "140979"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 170970,
      "SubModule": "Sale Quotation",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/SaleQuotation/Index",
      "IsParent": false,
      "ParentID": "140978"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 170971,
      "SubModule": "Sale Order",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/SaleOrder/Index",
      "IsParent": false,
      "ParentID": "140978"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 170974,
      "SubModule": "Delivery Note",
      "SubModuleOrder": "5",
      "Url": "/ProductManagement/DeliveryNote/Index",
      "IsParent": false,
      "ParentID": "140978"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 191215,
      "SubModule": "New Customer",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/Customer/Index",
      "IsParent": false,
      "ParentID": "191214"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 201216,
      "SubModule": "Sale Return Note",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/SalesInvoiceReturnNote/Index",
      "IsParent": false,
      "ParentID": "140978"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211270,
      "SubModule": "Sale Quotation Report",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/Reports/SaleQuotations",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211271,
      "SubModule": "Sale Orders Report",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/Reports/SaleOrders",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211272,
      "SubModule": "DN Report",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/Reports/DeliverOrders",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211273,
      "SubModule": "Sale Invoices Report",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/Reports/SaleInvoices",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211276,
      "SubModule": "Customer Ledger Balances Report",
      "SubModuleOrder": "5",
      "Url": "/ProductManagement/Reports/CustomerLedgerBalances",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211277,
      "SubModule": "Customer Transactions Report",
      "SubModuleOrder": "6",
      "Url": "/ProductManagement/Reports/CustomerTransactions",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211329,
      "SubModule": "Sale Invoice Detail Report",
      "SubModuleOrder": "7",
      "Url": "/ProductManagement/Reports/SaleInvoiceDetail",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211342,
      "SubModule": "Sale By Item Report",
      "SubModuleOrder": "8",
      "Url": "/ProductManagement/Reports/SaleByItem",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211363,
      "SubModule": "Customer Contact",
      "SubModuleOrder": "4",
      "Url": "/PointOfSale/CustomerContact/List",
      "IsParent": false,
      "ParentID": "191214"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211367,
      "SubModule": "Sale Return Invoice Report",
      "SubModuleOrder": "9",
      "Url": "/ProductManagement/Reports/SaleReturnInvoices",
      "IsParent": false,
      "ParentID": "211269"
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211368,
      "SubModule": "Invoice Type Group",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/InvoiceTypeGroup",
      "IsParent": false,
      "ParentID": "140979"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211345,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211349,
      "SubModule": "Screens",
      "SubModuleOrder": "1",
      "Url": "/Services/Setup/Screens",
      "IsParent": false,
      "ParentID": "211347"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211350,
      "SubModule": "Project",
      "SubModuleOrder": "2",
      "Url": "/Services/Project/List",
      "IsParent": false,
      "ParentID": "211346"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211351,
      "SubModule": "Timesheet",
      "SubModuleOrder": "3",
      "Url": "/Services/Timesheet/List",
      "IsParent": false,
      "ParentID": "211346"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211352,
      "SubModule": "Service Item",
      "SubModuleOrder": "1",
      "Url": "/Services/ServiceItem/List",
      "IsParent": false,
      "ParentID": "211357"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211355,
      "SubModule": "Subcontractor",
      "SubModuleOrder": "1",
      "Url": "/Services/Subcontractor/List",
      "IsParent": false,
      "ParentID": "211346"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211357,
      "SubModule": "Service Management",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211358,
      "SubModule": "Quotation",
      "SubModuleOrder": "2",
      "Url": "/Services/ServiceItemQuotation/List",
      "IsParent": false,
      "ParentID": "211357"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211359,
      "SubModule": "Invoice",
      "SubModuleOrder": "3",
      "Url": "/Services/ServiceItemInvoice/List",
      "IsParent": false,
      "ParentID": "211357"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211360,
      "SubModule": "Employee Timesheet",
      "SubModuleOrder": "4",
      "Url": "/Services/Employee/Timesheet",
      "IsParent": false,
      "ParentID": "211346"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140970,
      "SubModule": "Supply Chain Management",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140971,
      "SubModule": "DashBoard",
      "SubModuleOrder": "0",
      "Url": "/ProductManagement/SupplyChainDashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140972,
      "SubModule": "Settings",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140973,
      "SubModule": "Purchase Invoice",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/PurchaseInvoice/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140974,
      "SubModule": "Vendor Registration",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/VendorCard/Index",
      "IsParent": false,
      "ParentID": "140972"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 170965,
      "SubModule": "Purchase Order",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/PurchaseOrder/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 170968,
      "SubModule": "Goods Receive Note",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/GRN/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 201215,
      "SubModule": "Purchase Return Note",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/PurchaseInvoiceReturnNote/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 201243,
      "SubModule": "Supply Chain Setup",
      "SubModuleOrder": "6",
      "Url": "/ProductManagement/SupplyChainSetup/Index",
      "IsParent": false,
      "ParentID": "140972"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 201244,
      "SubModule": "Payment Terms",
      "SubModuleOrder": "7",
      "Url": "/ProductManagement/PaymentTerms/Index",
      "IsParent": false,
      "ParentID": "140972"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211251,
      "SubModule": "Other Charges",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/OtherCharges/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211265,
      "SubModule": "Reports",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211266,
      "SubModule": "Purchase Order Report",
      "SubModuleOrder": "1",
      "Url": "/ProductManagement/Reports/PurchaseOrders",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211267,
      "SubModule": "GRN Report",
      "SubModuleOrder": "2",
      "Url": "/ProductManagement/Reports/GoodsReceivedNotes",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211268,
      "SubModule": "Purchase Invoices Report",
      "SubModuleOrder": "3",
      "Url": "/ProductManagement/Reports/PurchaseInvoices",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211278,
      "SubModule": "Vendor Ledger Balances Report",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/Reports/VendorBalances",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211280,
      "SubModule": "Vendor Transactions Report",
      "SubModuleOrder": "4",
      "Url": "/ProductManagement/Reports/VendorTransactions",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211305,
      "SubModule": "Put-Away",
      "SubModuleOrder": "6",
      "Url": "/ProductManagement/PutAway/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211307,
      "SubModule": "Pick",
      "SubModuleOrder": "7",
      "Url": "/ProductManagement/Pick/Index",
      "IsParent": false,
      "ParentID": "140970"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211331,
      "SubModule": "Purchase Orders Summary Report",
      "SubModuleOrder": "6",
      "Url": "/ProductManagement/Reports/PurchaseOrderSummary",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211366,
      "SubModule": "VAT Setup Other Charges",
      "SubModuleOrder": "8",
      "Url": "/ProductManagement/VATSetup/index",
      "IsParent": false,
      "ParentID": "140972"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211371,
      "SubModule": "Purchase Return Invoice Report",
      "SubModuleOrder": "7",
      "Url": "/ProductManagement/Reports/PurchaseReturnInvoice",
      "IsParent": false,
      "ParentID": "211265"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 201245,
      "SubModule": "Profile",
      "SubModuleOrder": "2",
      "Url": "/TenantPortal/Profile/Index",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 201246,
      "SubModule": "Units",
      "SubModuleOrder": "3",
      "Url": "/TenantPortal/Unit/List",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 201248,
      "SubModule": "Family Member",
      "SubModuleOrder": "2",
      "Url": "/TenantPortal/FamilyMember/Detail",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 211247,
      "SubModule": "Agreement",
      "SubModuleOrder": "4",
      "Url": "/TenantPortal/LeaseAgreement/List",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 211263,
      "SubModule": "Maintenance Requests",
      "SubModuleOrder": "5",
      "Url": "/TenantPortal/MaintenanceRequest/List",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 211264,
      "SubModule": "Move Out Requests",
      "SubModuleOrder": "7",
      "Url": "/TenantPortal/MoveOutRequests/List",
      "IsParent": false,
      "ParentID": "211262"
    },
    {
      "ModuleID": 23,
      "Module": "Used Car",
      "ModuleOrder": 22,
      "SubModuleID": 211380,
      "SubModule": "Setups",
      "SubModuleOrder": "1",
      "Url": "/UsedCar/Setup/Screens",
      "IsParent": false,
      "ParentID": "211383"
    },
    {
      "ModuleID": 23,
      "Module": "Used Car",
      "ModuleOrder": 22,
      "SubModuleID": 211381,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "/UsedCar/Dashboard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 170995,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "/UsedCars/UsedCarsDashBoard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 170999,
      "SubModule": "After Modification",
      "SubModuleOrder": "1",
      "Url": "/UsedCars/AfterModification/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171001,
      "SubModule": "Appointment Module Setup",
      "SubModuleOrder": "2",
      "Url": "/UsedCars/AppointmentModuleSetup/AppointmentSetup",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171002,
      "SubModule": "Body Type",
      "SubModuleOrder": "2",
      "Url": "/UsedCars/BodyType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171003,
      "SubModule": "Car Condition Category",
      "SubModuleOrder": "3",
      "Url": "/UsedCars/CarConditionCategory/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171004,
      "SubModule": "Drive Type",
      "SubModuleOrder": "4",
      "Url": "/UsedCars/DriveType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171005,
      "SubModule": "Engine Capacity",
      "SubModuleOrder": "5",
      "Url": "/UsedCars/EngineCapacity/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171006,
      "SubModule": "Fuel Type",
      "SubModuleOrder": "6",
      "Url": "/UsedCars/FuelType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171007,
      "SubModule": "Vehicle Quick Notes",
      "SubModuleOrder": "7",
      "Url": "/UsedCars/QuickListRefNote/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171008,
      "SubModule": "Regional Spec",
      "SubModuleOrder": "8",
      "Url": "/UsedCars/RegionalSpec/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171009,
      "SubModule": "Supervisor Setup",
      "SubModuleOrder": "3",
      "Url": "/UsedCars/SupervisorSetup/SupervisorView",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171010,
      "SubModule": "Transmission",
      "SubModuleOrder": "9",
      "Url": "/UsedCars/Transmission/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171011,
      "SubModule": "Vehicle Appointment",
      "SubModuleOrder": "4",
      "Url": "/UsedCars/VehicleAppointment/VehicleAppointments",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171012,
      "SubModule": "Vehicle Info",
      "SubModuleOrder": "5",
      "Url": "/UsedCars/VehicleInfo/VehicleInfoView",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171013,
      "SubModule": "Vehicle Inspection",
      "SubModuleOrder": "6",
      "Url": "/UsedCars/VehicleInspection/VehicleInspectionView",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171014,
      "SubModule": "Vehicle Inspection Head",
      "SubModuleOrder": "10",
      "Url": "/UsedCars/VehicleInspectionHead/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 171015,
      "SubModule": "Vehicle Inspection Detail",
      "SubModuleOrder": "11",
      "Url": "/UsedCars/VehicleInspectionRefDetail/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181070,
      "SubModule": "Make",
      "SubModuleOrder": "12",
      "Url": "/UsedCars/Make/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181071,
      "SubModule": "Quick Notes",
      "SubModuleOrder": "13",
      "Url": "/UsedCars/QuickListRefNote/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181072,
      "SubModule": "Vehicle Receiving Note",
      "SubModuleOrder": "7",
      "Url": "/UsedCars/VehicleReceivingNote/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181073,
      "SubModule": "Vehicle Purchase Order",
      "SubModuleOrder": "8",
      "Url": "/UsedCars/VehiclePurchaseOrder/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181074,
      "SubModule": "Model",
      "SubModuleOrder": "14",
      "Url": "/UsedCars/VehicleModel/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181075,
      "SubModule": "Vehicle Parking",
      "SubModuleOrder": "10",
      "Url": "/UsedCars/VehicleParkingHead/VehicleParkingHeadIndex",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181076,
      "SubModule": "Vehicle Parking Type",
      "SubModuleOrder": "15",
      "Url": "/UsedCars/VehicleParkingType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181077,
      "SubModule": "Vehicle Parking Detail",
      "SubModuleOrder": "11",
      "Url": "/UsedCars/VehicleParkingDetail/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181078,
      "SubModule": "Vehicle Parking Allotment",
      "SubModuleOrder": "12",
      "Url": "/UsedCars/VehicleParkingSlot/VehicleParkingAllotment",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181088,
      "SubModule": "Vehicle Key",
      "SubModuleOrder": "16",
      "Url": "/UsedCars/VehicleKeyInformation/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181089,
      "SubModule": "Vehicle Key Type",
      "SubModuleOrder": "17",
      "Url": "/UsedCars/VehicleKeyType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181090,
      "SubModule": "Vehicle Type",
      "SubModuleOrder": "18",
      "Url": "/UsedCars/VehicleType/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181093,
      "SubModule": "Vehicle Key Status",
      "SubModuleOrder": "19",
      "Url": "/UsedCars/VehicleRefKeyStatus/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181094,
      "SubModule": "Vehicle Service",
      "SubModuleOrder": "19",
      "Url": "/UsedCars/VehicleService/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181126,
      "SubModule": "Exterior Color",
      "SubModuleOrder": "21",
      "Url": "/UsedCars/VehicleExteriorColor/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181127,
      "SubModule": "Interior Color",
      "SubModuleOrder": "21",
      "Url": "/UsedCars/VehicleInteriorColor/Index",
      "IsParent": false,
      "ParentID": "170998"
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 181134,
      "SubModule": "Vehicle Purchase Offer",
      "SubModuleOrder": "23",
      "Url": "/UsedCars/VehiclePurchaseOffer/Index",
      "IsParent": false,
      "ParentID": "170996"
    },
    {
      "ModuleID": 25,
      "Module": "Video Chat",
      "ModuleOrder": 28,
      "SubModuleID": 181117,
      "SubModule": "Generate Meeting",
      "SubModuleOrder": "1",
      "Url": "/VideoChat/Meeting/Generate",
      "IsParent": false,
      "ParentID": "181116"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 181159,
      "SubModule": "Dashboard",
      "SubModuleOrder": "1",
      "Url": "/WarehouseManagement/DashBoard/Index",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 181162,
      "SubModule": "Warehouse Setup",
      "SubModuleOrder": "5",
      "Url": "/WarehouseManagement/Warehouse/Index",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 181164,
      "SubModule": "Warehouse List",
      "SubModuleOrder": "2",
      "Url": "/WarehouseManagement/WarehouseList/Index",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 211275,
      "SubModule": "Level Size",
      "SubModuleOrder": "1",
      "Url": "/WarehouseManagement/WarehouseLevelSize/Index",
      "IsParent": false,
      "ParentID": "181160"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 211316,
      "SubModule": "Transfer Out",
      "SubModuleOrder": "6",
      "Url": "/WarehouseManagement/TransferOut/Index",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 211317,
      "SubModule": "Transfer In",
      "SubModuleOrder": "8",
      "Url": "/WarehouseManagement/TransferIn/Index",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 211354,
      "SubModule": "Consignee Warehouse ",
      "SubModuleOrder": "7",
      "Url": "/WarehouseManagement/ConsigneeWarehouse/Index",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 211372,
      "SubModule": "Location wise Inventory",
      "SubModuleOrder": "9",
      "Url": "/WarehouseManagement/LocationWiseInventory/List",
      "IsParent": false,
      "ParentID": "181155"
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 28,
      "SubModule": "Settings",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 170976,
      "SubModule": "Accounts Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181108,
      "SubModule": "Treasury",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 181173,
      "SubModule": "Tax",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 2,
      "Module": "Accounts ",
      "ModuleOrder": 2,
      "SubModuleID": 201238,
      "SubModule": "Reports",
      "SubModuleOrder": "5",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171023,
      "SubModule": "Asset Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 6,
      "Module": "Assets ",
      "ModuleOrder": 8,
      "SubModuleID": 171024,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 50616,
      "SubModule": "Settings",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 4,
      "Module": "Attendance & Leave",
      "ModuleOrder": 4,
      "SubModuleID": 171020,
      "SubModule": "Attendance & Leave",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211287,
      "SubModule": "Cash Center",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211290,
      "SubModule": "Vouchers",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211291,
      "SubModule": "Role Type",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10040,
      "Module": "Cash Center",
      "ModuleOrder": 6,
      "SubModuleID": 211321,
      "SubModule": "Reports",
      "SubModuleOrder": "5",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 1,
      "SubModule": "User Management",
      "SubModuleOrder": null,
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 130792,
      "SubModule": "Global Settings",
      "SubModuleOrder": "18",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 1,
      "Module": "ERP Core",
      "ModuleOrder": 1,
      "SubModuleID": 140942,
      "SubModule": "Company Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 201249,
      "SubModule": "Asset Management",
      "SubModuleOrder": "1",
      "Url": " #",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 201250,
      "SubModule": "Settings",
      "SubModuleOrder": "2",
      "Url": " ",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 39,
      "Module": "Fixed Assets",
      "ModuleOrder": 9,
      "SubModuleID": 211253,
      "SubModule": "Reports",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 10116,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 10131,
      "SubModule": "Employee Management",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 3,
      "Module": "HR ",
      "ModuleOrder": 3,
      "SubModuleID": 211312,
      "SubModule": "Reports",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181111,
      "SubModule": "Request Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 181112,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 24,
      "Module": "Job Request Center",
      "ModuleOrder": 27,
      "SubModuleID": 201236,
      "SubModule": "Reports",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 10041,
      "Module": "Landlord Portal",
      "ModuleOrder": 31,
      "SubModuleID": 211296,
      "SubModule": "LandLord Portal",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 10193,
      "SubModule": "Settings",
      "SubModuleOrder": "5",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 5,
      "Module": "Payroll ",
      "ModuleOrder": 5,
      "SubModuleID": 171018,
      "SubModule": "Payroll Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 13,
      "Module": "Point Of Sale",
      "ModuleOrder": 25,
      "SubModuleID": 181095,
      "SubModule": "Sale Management",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 13,
      "Module": "Point Of Sale",
      "ModuleOrder": 25,
      "SubModuleID": 211336,
      "SubModule": "Settings",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140944,
      "SubModule": "Settings",
      "SubModuleOrder": "21",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 140956,
      "SubModule": "Product Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 19,
      "Module": "Product ",
      "ModuleOrder": 19,
      "SubModuleID": 211339,
      "SubModule": "Reports",
      "SubModuleOrder": "22",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171054,
      "SubModule": "Property Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 171057,
      "SubModule": "Settings",
      "SubModuleOrder": "6",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181145,
      "SubModule": "Reports",
      "SubModuleOrder": "7",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181185,
      "SubModule": "Leasing",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181186,
      "SubModule": "Landlord",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 22,
      "Module": "Real Estate",
      "ModuleOrder": 24,
      "SubModuleID": 181187,
      "SubModule": "Tenant",
      "SubModuleOrder": "5",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 40596,
      "SubModule": "Booking Management",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 130912,
      "SubModule": "Token Reports",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140927,
      "SubModule": "Recovery Reports",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140978,
      "SubModule": "Sales Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 140979,
      "SubModule": "Settings",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 191214,
      "SubModule": "Customer",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 20,
      "Module": "Sales ",
      "ModuleOrder": 21,
      "SubModuleID": 211269,
      "SubModule": "Reports",
      "SubModuleOrder": "7",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211346,
      "SubModule": "Project Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211347,
      "SubModule": "Settings",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 10045,
      "Module": "Services",
      "ModuleOrder": 32,
      "SubModuleID": 211357,
      "SubModule": "Service Management",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140970,
      "SubModule": "Supply Chain Management",
      "SubModuleOrder": "1",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 140972,
      "SubModule": "Settings",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 9,
      "Module": "Supply Chain ",
      "ModuleOrder": 20,
      "SubModuleID": 211265,
      "SubModule": "Reports",
      "SubModuleOrder": "4",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 10039,
      "Module": "Tenant Portal",
      "ModuleOrder": 30,
      "SubModuleID": 211262,
      "SubModule": "Tenant Portal Management",
      "SubModuleOrder": "1",
      "Url": "/",
      "IsParent": true,
      "ParentID": "0"
    },
    {
      "ModuleID": 23,
      "Module": "Used Car",
      "ModuleOrder": 22,
      "SubModuleID": 211383,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 170996,
      "SubModule": "Used Cars",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 21,
      "Module": "Used Cars - Old",
      "ModuleOrder": 23,
      "SubModuleID": 170998,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 25,
      "Module": "Video Chat",
      "ModuleOrder": 28,
      "SubModuleID": 181116,
      "SubModule": "Meetings Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 181155,
      "SubModule": "WareHouse Management",
      "SubModuleOrder": "2",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    },
    {
      "ModuleID": 26,
      "Module": "Warehouse ",
      "ModuleOrder": 29,
      "SubModuleID": 181160,
      "SubModule": "Settings",
      "SubModuleOrder": "3",
      "Url": "#",
      "IsParent": true,
      "ParentID": null
    }
  ];